# Generated by Django 5.1.5 on 2025-01-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_counting_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counting',
            name='text_file',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='word',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
